# This is a basic workflow to help you get started with Actions

name: TWRP_laurel_sprout_9.0

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the android-9.0 branch
  push:
    branches: [ android-9.0 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Build
      - name: Build, nice
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          sudo apt-get update
          sudo apt-get install git -y
          cd ~
          git clone https://github.com/hendramanu/githubactions-ci && cd githubactions-ci
          ./twrp.sh laurel_sprout 9.0 eng boot
